// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: media.proto

package media

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MediaService_GetMediaByID_FullMethodName    = "/media.MediaService/GetMediaByID"
	MediaService_GetMediasByName_FullMethodName = "/media.MediaService/GetMediasByName"
	MediaService_SaveMedia_FullMethodName       = "/media.MediaService/SaveMedia"
	MediaService_UpdateMedia_FullMethodName     = "/media.MediaService/UpdateMedia"
	MediaService_SearchTMDB_FullMethodName      = "/media.MediaService/SearchTMDB"
)

// MediaServiceClient is the client API for MediaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MediaServiceClient interface {
	GetMediaByID(ctx context.Context, in *GetMediaByIDRequest, opts ...grpc.CallOption) (*Media, error)
	GetMediasByName(ctx context.Context, in *GetMediasByNameRequest, opts ...grpc.CallOption) (*MediaList, error)
	SaveMedia(ctx context.Context, in *SaveMediaRequest, opts ...grpc.CallOption) (*Media, error)
	UpdateMedia(ctx context.Context, in *SaveMediaRequest, opts ...grpc.CallOption) (*Media, error)
	SearchTMDB(ctx context.Context, in *SearchTMDBRequest, opts ...grpc.CallOption) (*SearchTMDBResponse, error)
}

type mediaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaServiceClient(cc grpc.ClientConnInterface) MediaServiceClient {
	return &mediaServiceClient{cc}
}

func (c *mediaServiceClient) GetMediaByID(ctx context.Context, in *GetMediaByIDRequest, opts ...grpc.CallOption) (*Media, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Media)
	err := c.cc.Invoke(ctx, MediaService_GetMediaByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) GetMediasByName(ctx context.Context, in *GetMediasByNameRequest, opts ...grpc.CallOption) (*MediaList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MediaList)
	err := c.cc.Invoke(ctx, MediaService_GetMediasByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) SaveMedia(ctx context.Context, in *SaveMediaRequest, opts ...grpc.CallOption) (*Media, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Media)
	err := c.cc.Invoke(ctx, MediaService_SaveMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) UpdateMedia(ctx context.Context, in *SaveMediaRequest, opts ...grpc.CallOption) (*Media, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Media)
	err := c.cc.Invoke(ctx, MediaService_UpdateMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) SearchTMDB(ctx context.Context, in *SearchTMDBRequest, opts ...grpc.CallOption) (*SearchTMDBResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchTMDBResponse)
	err := c.cc.Invoke(ctx, MediaService_SearchTMDB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MediaServiceServer is the server API for MediaService service.
// All implementations must embed UnimplementedMediaServiceServer
// for forward compatibility.
type MediaServiceServer interface {
	GetMediaByID(context.Context, *GetMediaByIDRequest) (*Media, error)
	GetMediasByName(context.Context, *GetMediasByNameRequest) (*MediaList, error)
	SaveMedia(context.Context, *SaveMediaRequest) (*Media, error)
	UpdateMedia(context.Context, *SaveMediaRequest) (*Media, error)
	SearchTMDB(context.Context, *SearchTMDBRequest) (*SearchTMDBResponse, error)
	mustEmbedUnimplementedMediaServiceServer()
}

// UnimplementedMediaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMediaServiceServer struct{}

func (UnimplementedMediaServiceServer) GetMediaByID(context.Context, *GetMediaByIDRequest) (*Media, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMediaByID not implemented")
}
func (UnimplementedMediaServiceServer) GetMediasByName(context.Context, *GetMediasByNameRequest) (*MediaList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMediasByName not implemented")
}
func (UnimplementedMediaServiceServer) SaveMedia(context.Context, *SaveMediaRequest) (*Media, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveMedia not implemented")
}
func (UnimplementedMediaServiceServer) UpdateMedia(context.Context, *SaveMediaRequest) (*Media, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMedia not implemented")
}
func (UnimplementedMediaServiceServer) SearchTMDB(context.Context, *SearchTMDBRequest) (*SearchTMDBResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchTMDB not implemented")
}
func (UnimplementedMediaServiceServer) mustEmbedUnimplementedMediaServiceServer() {}
func (UnimplementedMediaServiceServer) testEmbeddedByValue()                      {}

// UnsafeMediaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaServiceServer will
// result in compilation errors.
type UnsafeMediaServiceServer interface {
	mustEmbedUnimplementedMediaServiceServer()
}

func RegisterMediaServiceServer(s grpc.ServiceRegistrar, srv MediaServiceServer) {
	// If the following call pancis, it indicates UnimplementedMediaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MediaService_ServiceDesc, srv)
}

func _MediaService_GetMediaByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMediaByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).GetMediaByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_GetMediaByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).GetMediaByID(ctx, req.(*GetMediaByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_GetMediasByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMediasByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).GetMediasByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_GetMediasByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).GetMediasByName(ctx, req.(*GetMediasByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_SaveMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).SaveMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_SaveMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).SaveMedia(ctx, req.(*SaveMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_UpdateMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).UpdateMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_UpdateMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).UpdateMedia(ctx, req.(*SaveMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_SearchTMDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTMDBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).SearchTMDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_SearchTMDB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).SearchTMDB(ctx, req.(*SearchTMDBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MediaService_ServiceDesc is the grpc.ServiceDesc for MediaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "media.MediaService",
	HandlerType: (*MediaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMediaByID",
			Handler:    _MediaService_GetMediaByID_Handler,
		},
		{
			MethodName: "GetMediasByName",
			Handler:    _MediaService_GetMediasByName_Handler,
		},
		{
			MethodName: "SaveMedia",
			Handler:    _MediaService_SaveMedia_Handler,
		},
		{
			MethodName: "UpdateMedia",
			Handler:    _MediaService_UpdateMedia_Handler,
		},
		{
			MethodName: "SearchTMDB",
			Handler:    _MediaService_SearchTMDB_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "media.proto",
}
